# Generated by Django 5.1.3 on 2024-12-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
